const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const ts = require('typescript')
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, esModuleInterop: true } }).outputText, filename)
const { calculateLivePix } = require('../src/livePix.ts')
const { buildClosingWorkbook, approvedClosingRecords } = require('../src/closingWorkbook.ts')
const { gerarPayloadPixEstatico } = require('../src/pixPayload.ts')
const { buildClosingPDF, closingPDFMatrix } = require('../src/pdfExport.ts')
const worker = { id: 'a', nome: 'Ana', funcao: 'Operadora', chavePix: 'ana@example.com', titularPix: 'Ana', cidadePix: 'Mogi Mirim' }
const daily = { id: '1', employeeId: 'a', nome: 'Ana', funcao: 'Operadora', data: '01/09/2026', status: 'Aprovada', diariaBase: 100, adicional: 10, vt: 8, vr: 12, valor: 130 }
const period = '01/09/2026 a 15/09/2026'
const calculate = (rows, payments = [], workers = [worker]) => calculateLivePix(workers, rows, payments, period, '2026-09-01', '2026-09-15')

test('PIX includes only approved daily records in the current period, including boundaries', () => {
  const result = calculate([daily, {...daily, data: '15/09/2026'}, {...daily, status: 'Pendente'}, {...daily, status: 'Cancelada'}, {...daily, data: '16/09/2026'}, {...daily, data: '31/08/2026'}])
  assert.equal(result[0].valorTotal, 260)
  assert.equal(result[0].quantidadeDiarias, 2)
  assert.equal(result[0].pix, worker.chavePix)
})
test('PIX subtracts paid and processing amounts without subtracting awaiting payments twice', () => {
  const payment = { employeeId: 'a', nome: 'Ana', periodo: period, valorTotal: 20 }
  const result = calculate([daily], [{...payment, status:'Pago'}, {...payment, status:'Processando'}, {...payment, status:'Aguardando'}, {...payment, status:'Pago', periodo:'outro'}])
  assert.equal(result[0].valorTotal, 90)
  assert.equal(calculate([daily], [{...payment, status:'Pago', valorTotal:200}])[0].valorTotal, 0)
})
test('PIX keeps people with the same name separate and does not assign ambiguous legacy entries', () => {
  const result = calculate([daily, {...daily, employeeId: undefined}], [], [worker, {...worker, id:'b'}])
  assert.equal(result.length, 2)
  assert.equal(result[0].valorTotal, 130)
})
test('PIX updates from fresh approved amounts with exact cents', () => {
  assert.equal(calculate([{...daily, valor:0.1}, {...daily, valor:0.2}])[0].valorTotal, 0.3)
  assert.equal(calculate([{...daily, status:'Pendente'}])[0].valorTotal, 0)
})
test('PIX retains cards before any approved daily record and after payment', () => {
  assert.equal(calculate([]).length, 1)
  assert.equal(calculate([])[0].quantidadeDiarias, 0)
  assert.equal(calculate([daily], [{employeeId:'a',nome:'Ana',periodo:period,status:'Pago',valorTotal:130}])[0].valorTotal, 0)
})
test('zero-balance directory QR omits the amount field while payable QR includes it', () => {
  const props = { chave:'ana@example.com',tipoChave:'E-mail',titular:'Ana',cidade:'Mogi Mirim',valor:0 }
  const fields = payload => { const result={}; let index=0; while(index<payload.length){ const id=payload.slice(index,index+2);const size=Number(payload.slice(index+2,index+4));result[id]=payload.slice(index+4,index+4+size);index+=4+size } return result }
  const open = fields(gerarPayloadPixEstatico({...props, permitirSemValor:true}))
  assert.equal(open['54'],undefined)
  assert.equal(open['63'].length,4)
  assert.equal(fields(gerarPayloadPixEstatico({...props,valor:130.25}))['54'],'130.25')
  assert.throws(()=>gerarPayloadPixEstatico(props),/maior que zero/)
  assert.throws(()=>gerarPayloadPixEstatico({...props,valor:-1,permitirSemValor:true}),/maior que zero/)
})
test('closing PDF paginates long lists and remains a valid PDF', () => {
  const records=Array.from({length:70},(_,index)=>({...daily,employeeId:String(index),nome:`Trabalhador ${index} com sobrenome para conferir quebra de linha`}))
  const doc=buildClosingPDF({periodo:period,pagamento:'20/09/2026',status:'Aprovado',dates:[new Date(2026,8,1)],records})
  assert.ok(doc.getNumberOfPages()>1)
  assert.ok(doc.output().startsWith('%PDF-'))
  assert.ok(doc.output().includes('9100') || doc.output().includes('9.100'))
})
test('PDF spreadsheet has daily columns, sums repeated daily records and excludes unapproved entries', () => {
  const matrix = closingPDFMatrix({periodo:period,pagamento:'20/09/2026',status:'Aprovado',dates:[new Date(2026,8,1),new Date(2026,8,2)],records:[daily,{...daily,id:'2',valor:50},{...daily,id:'3',status:'Pendente'}],dailyRecordIds:['1','2','3']})
  assert.deepEqual(matrix.headers.slice(1,3),['01/09','02/09'])
  assert.deepEqual(matrix.rows[0].slice(1,3),['180,00','-'])
  assert.equal(matrix.rows[0].at(-1),'180,00')
  assert.equal(matrix.totals[1],'180,00')
  assert.equal(matrix.totals.length,matrix.headers.length)
})
test('Excel exports approved linked records, numeric values, formulas and formatted sheets', async () => {
  const input = {periodo:period, pagamento:'20/09/2026', status:'Fechado', dates:[new Date(2026,8,1),new Date(2026,8,2)], records:[daily, {...daily,id:'2',valor:50}, {...daily,id:'3',status:'Pendente'}, {...daily,id:'4'}], dailyRecordIds:['1','2','3']}
  assert.equal(approvedClosingRecords(input).length, 2)
  assert.equal(approvedClosingRecords({...input,dailyRecordIds:[]}).length, 0)
  const book = buildClosingWorkbook(input)
  const sheet = book.getWorksheet('Mapa diário')
  assert.equal(sheet.getCell('D7').result, 180)
  assert.match(sheet.getCell('D7').formula, /SUMIFS/)
  assert.equal(sheet.getCell('J7').result, 180)
  assert.equal(sheet.getCell('J8').result, 180)
  assert.equal(sheet.views[0].ySplit, 6)
  assert.equal(book.getWorksheet('Lançamentos').getCell('I5').value, 130)
  assert.ok(book.getWorksheet('Lançamentos').getCell('D5').value instanceof Date)
  const summary = book.getWorksheet('Fechamento')
  assert.equal(book.worksheets[0].name, 'Mapa diário')
  assert.equal(summary.getCell('G6').result, 180)
  assert.equal(summary.getCell('G7').result, 180)
  assert.equal(summary.columnCount, 7)
  const buffer = await book.xlsx.writeBuffer()
  const restored = new (require('exceljs').Workbook)()
  await restored.xlsx.load(buffer)
  assert.equal(restored.getWorksheet('Fechamento').getCell('G6').result, 180)
  assert.ok(restored.getWorksheet('Fechamento').getCell('G6').numFmt.includes('#,##0.00'))
  assert.equal(restored.getWorksheet('Fechamento').pageSetup.orientation, 'landscape')
})
