import { useState } from 'react'
import type { LivePixItem } from './livePix'
import { SystemIcon } from './AdminShell'
const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })

export default function LivePixPanel({ items, period, onOpen, onCopy, onEdit }: { items: LivePixItem[]; period: string; onOpen: (item: LivePixItem) => void; onCopy: (key: string) => void; onEdit?: (item: LivePixItem) => void }) {
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('Todos')
  const situation = (item: LivePixItem) => !item.pix ? 'Cadastrar PIX' : !item.pixCidade ? 'Completar cadastro' : !item.quantidadeDiarias ? 'Sem diárias aprovadas' : item.valorTotal > 0 ? 'Saldo a pagar' : item.reservado > 0 ? 'Em processamento' : 'Quitado'
  const visible = items.filter(item => item.nome.toLocaleLowerCase('pt-BR').includes(search.trim().toLocaleLowerCase('pt-BR')) && (status === 'Todos' || situation(item) === status))
  return <section className="live-pix-panel">
    <div className="live-pix-heading"><div><span className="section-label">QUINZENA ATUAL · {period}</span><h2>Central PIX</h2><p>Todos os trabalhadores, sempre disponíveis. O saldo acompanha as diárias aprovadas da quinzena.</p></div><div className="live-pix-total"><span>Saldo aprovado disponível</span><strong>{money(items.reduce((sum, item) => sum + item.valorTotal, 0))}</strong><small>Pagamentos confirmados e em processamento descontados</small></div></div>
    <div className="pix-toolbar"><label className="live-pix-search"><SystemIcon name="search"/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar trabalhador" aria-label="Buscar trabalhador na Central PIX"/></label><select aria-label="Situação do PIX" value={status} onChange={event => setStatus(event.target.value)}>{['Todos', 'Saldo a pagar', 'Quitado', 'Sem diárias aprovadas', 'Em processamento', 'Cadastrar PIX', 'Completar cadastro'].map(value => <option key={value}>{value}</option>)}</select><span>{visible.length} de {items.length} trabalhadores</span></div>
    <div className="live-pix-grid">{visible.map(item => <article className="live-pix-worker" key={item.previsaoKey}><div className="live-pix-worker-heading"><span>{item.nome.split(' ').filter(Boolean).slice(0, 2).map(word => word[0]).join('')}</span><div><h3>{item.nome}</h3><small>{item.funcao}</small></div></div><span className={`pix-situation ${item.valorTotal > 0 ? "has-balance" : ""}`}>{situation(item)}</span><dl><div><dt>Diárias aprovadas</dt><dd>{item.quantidadeDiarias}</dd></div><div><dt>Total aprovado</dt><dd>{money(item.aprovado)}</dd></div><div><dt>Já pago</dt><dd>{money(item.pago)}</dd></div>{item.reservado > 0 && <div><dt>Em processamento</dt><dd>{money(item.reservado)}</dd></div>}</dl><div className="live-pix-balance"><span>Saldo disponível</span><strong>{money(item.valorTotal)}</strong></div><div className="pix-identity"><small>TITULAR</small><strong>{item.pixTitular}</strong><small>CHAVE PIX</small></div><p className="live-pix-key">{item.pix || 'Chave PIX não cadastrada'}</p><div className="pix-card-actions"><button className="primary-button" disabled={!item.pix || !item.pixCidade} onClick={() => onOpen(item)}><SystemIcon name="wallet"/> Ver QR Code</button><button className="secondary-button" disabled={!item.pix} onClick={() => onCopy(item.pix)}>Copiar chave</button></div>{(!item.pix || !item.pixCidade) && onEdit && <button className="pix-edit" onClick={() => onEdit(item)}>Completar dados PIX →</button>}{item.pix && item.pixCidade && item.valorTotal === 0 && <small className="live-pix-missing">QR sem valor definido: informe o valor no banco.</small>}{!item.pixCidade && <small className="live-pix-missing">Cadastre a cidade do titular na ficha do trabalhador.</small>}</article>)}</div>
    {!visible.length && <div className="empty-filter-result">{items.length ? 'Nenhum trabalhador corresponde aos filtros.' : 'Cadastre trabalhadores para visualizar seus cards PIX.'}</div>}
    <p className="live-pix-footnote">Os cards permanecem aqui após o fechamento e o pagamento. O histórico e a confirmação dos pagamentos vinculados aos fechamentos continuam abaixo.</p>
  </section>
}
